name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22", "1.x"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Test build
        run: go build -v ./...

      - name: Test
        run: go test ./...

      - name: go vet
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          # cache-key: ${{ matrix.go-version }}

      - name: Run Gosec Security Scanner
        if: runner.os == 'Linux'
        uses: securego/gosec@master
        with:
          args: ./...
